auctions/urls.py
from django.core.exceptions import ViewDoesNotExist
from django.urls import path

from . import views


app_name = 'auctions'
urlpatterns = [
    path("", views.index, name="index"),
    path("login/", views.login_view, name="login"),
    path("logout/", views.logout_view, name="logout"),
    path("register/", views.register, name="register"),
    path("create-listing/", views.create_listing, name='create-listing'),
    path("listings/<int:id>", views.listing_detail, name='listing-detail'),
    path("categories/", views.categories, name='categories'),
    path("watchlist/", views.watchlist, name='watchlist'),
    path("close-listing/", views.close_listing, name='close-listing'),
    path("inactive/", views.inactive, name='inactive'),
    path("comment/", views.comment, name="comment")
]

commerce/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("auctions.urls"))
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

auctions/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.db.models.fields.files import ImageField


class User(AbstractUser):
    watchlist = models.ManyToManyField("Listing", related_name="watchlisters")


class Listing(models.Model):
    title = models.CharField(max_length=50)
    description = models.TextField()
    price = models.IntegerField()
    image = models.ImageField(upload_to='listing/')
    category = models.CharField(max_length=50, blank=True, null=True)
    created = models.DateTimeField(auto_now_add=True)
    closed = models.DateTimeField(blank=True, null=True)
    number_of_bids = models.IntegerField(default=0)
    is_active = models.BooleanField(default=True)
    winner = models.CharField(max_length=50, blank=True, null=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self) -> str:
        return self.title

class Bid(models.Model):
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    listing_id = models.ForeignKey(Listing, on_delete=models.CASCADE)
    bid_amount = models.IntegerField()


    def __str__(self) -> str:
        return str(self.bid_amount)

class Comment(models.Model):
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    listing_id = models.ForeignKey(Listing, on_delete=models.CASCADE)
    text = models.TextField()


    def __str__(self) -> str:
        return self.owner.username

auctions/forms.py
from django import forms
from django.contrib.admin.helpers import checkbox
from django.forms.widgets import Textarea
from .models import Comment, Bid, Listing


class ListingForm(forms.Form):
    title = forms.CharField(max_length=50)
    description = forms.CharField(max_length=255, widget=forms.Textarea)
    price = forms.IntegerField()
    image = forms.ImageField()
    category = forms.CharField(max_length=50)
    # class Meta:
    #     model = Listing
    #     fields = ['title', 'description', 'bid_amount', 'image', 'category']

class BidForm(forms.Form):
    bid_amount = forms.IntegerField(help_text="Your bid")

auctions/views.py
from django.contrib.auth import authenticate, login, logout
from django.db import IntegrityError
from django.db.models.expressions import Col, F
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from auctions.forms import ListingForm, BidForm
from auctions.models import User, Listing, Comment, Bid
from . import utils
import datetime


def index(request):
    listings = Listing.objects.filter(is_active=True)
    comments = Comment.objects.all()
    context = {
        "listings": listings,
    }
    return render(request, "auctions/index.html", context)


def login_view(request):
    if request.method == "POST":

        # Attempt to sign user in
        username = request.POST["username"]
        password = request.POST["password"]
        user = authenticate(request, username=username, password=password)

        # Check if authentication successful
        if user is not None:
            login(request, user)
            return HttpResponseRedirect(reverse("auctions:index"))
        else:
            return render(request, "auctions/login.html", {
                "message": "Invalid username and/or password."
            })
    else:
        return render(request, "auctions/login.html")


def logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse("auctions:index"))


def register(request):
    if request.method == "POST":
        username = request.POST["username"]
        email = request.POST["email"]

        # Ensure password matches confirmation
        password = request.POST["password"]
        confirmation = request.POST["confirmation"]
        if password != confirmation:
            return render(request, "auctions/register.html", {
                "message": "Passwords must match."
            })

        # Attempt to create new user
        try:
            user = User.objects.create_user(username, email, password)
            user.save()
        except IntegrityError:
            return render(request, "auctions/register.html", {
                "message": "Username already taken."
            })
        login(request, user)
        return HttpResponseRedirect(reverse("auctions:index"))
    else:
        return render(request, "auctions/register.html")
@login_required
def create_listing(request):
    if request.method == "POST":
        print(request.user.id)

        form = ListingForm(request.POST, request.FILES)
        print(form.is_valid())
        if form.is_valid():
            form.cleaned_data['owner'] = request.user
            listing = Listing.objects.create(**form.cleaned_data)
            return HttpResponseRedirect(reverse("auctions:index"))
        return render(request, 'auctions/create_listing.html', {
            "form": form
        })
    return render(request, 'auctions/create_listing.html', {
        'form': ListingForm()
    })
@login_required
def listing_detail(request, id):
    comments = Comment.objects.filter(listing_id=id)
    if request.method == "POST":
        form = BidForm(request.POST)
        if form.is_valid():
            max_bid = utils.get_max_bid(Bid.objects.filter(listing_id=id))
            if max_bid < form.cleaned_data['bid_amount']:
                Bid.objects.create(listing_id=Listing.objects.get(id=id), 
                owner=request.user, 
                bid_amount=form.cleaned_data['bid_amount']
                )
                L_object = Listing.objects.get(id=id)
                L_object.number_of_bids += 1
                L_object.save()
                
                return HttpResponseRedirect(reverse('auctions:listing-detail', args=(id,)))
            else:
                error = "You must enter more than current bid."
                context = {
                    "listing": Listing.objects.get(id=id),
                    "form": BidForm(),
                    "error": error,
                    "current_bid": max_bid,
                    "comments": comments
                }
                return render(request, "auctions/listing_detail.html", context)    
        listing = Listing.objects.get(id=id)
        current_bid = Bid.objects.filter(listing_id=listing)
        try:
            current_bid = current_bid[len(current_bid)-1]
        except:
            current_bid = 0
        context = {
            "listing": Listing.objects.get(id=id),
            "form": form,
            "current_bid": current_bid[len(current_bid)-1],
            "comments": comments
        }
        return render(request, "auctions/listing_detail.html", context)
    try:
        listing = Listing.objects.get(id=id)
        current_bid = Bid.objects.filter(listing_id=listing)
    except Listing.DoesNotExist:
        raise ValueError("Listing was not found.")
    try:
        current_bid = current_bid[len(current_bid)-1]
    except:
        current_bid = 0
    context = {
        "listing": listing,
        "form": BidForm(),
        "current_bid": current_bid,
        "comments": comments
    }
    return render(request, "auctions/listing_detail.html", context)

def categories(request):
    listings = []
    for listing in Listing.objects.all():
        if listing.category not in listings:
            listings.append(listing)
    context = {
        "listings": listings
    }
    return render(request, "auctions/categories.html", context)

# def list_categories(request, category):
#     listings = []
#     for listing in Listing.objects.all():
#         if listing.category == category:
#             listings.append(listing)
#     context = {
#         "listings": listings
#     }
#     return render(request, "auctions/list_categories.html", context)
@login_required
def watchlist(request):
    if request.method == "POST":
        watchlist_id = request.POST['watchlist_id']            
        listing_obj = Listing.objects.get(id=watchlist_id)
        if bool(int(request.POST['add'])):
            request.user.watchlist.add(listing_obj)
            return HttpResponseRedirect(reverse("auctions:watchlist"))
        request.user.watchlist.remove(listing_obj)
        return HttpResponseRedirect(reverse("auctions:watchlist"))
    watchlists = request.user.watchlist.all()
    context = {
        "watchlists": watchlists
    }
    return render(request, "auctions/watchlist.html", context)

def close_listing(request):
    if request.method == "POST":
        closing_obj_id = request.POST['close_id']
        bids = Bid.objects.filter(listing_id=int(closing_obj_id))
        max_bid = 0
        for bid in bids:
            if bid.bid_amount > max_bid:
                max_bid = bid.bid_amount
                winner = bid.owner.username
        listing = Listing.objects.get(id=int(closing_obj_id))
        listing.is_active = False
        listing.winner = winner
        listing.closed = datetime.datetime.now()
        listing.save()
        return HttpResponseRedirect(reverse("auctions:listing-detail", args=(int(closing_obj_id), )))
    
def inactive(request):
    listings = Listing.objects.filter(is_active=False)
    context = {
        "listings": listings
    }
    return render(request, "auctions/inactive.html", context)

def comment(request):
    if request.method == "POST":
        comment = Comment.objects.create(owner=request.user, 
                               listing_id=Listing.objects.get(id=int(request.POST['id'])),
                               text=request.POST['comment']
                               )
        comment.save()
        return HttpResponseRedirect(reverse("auctions:listing-detail", args=(int(request.POST['id']), )))

auctions/templates/auctions/categories.html
{% extends 'auctions/layout.html' %}
{% block title %}
    Categories
{% endblock %}
{% block body %}
    {% for listing in listings %}
        <ul>
            <li><a href="{% url 'auctions:listing-detail' listing.id %}">{{listing.category}}</a></li>
        </ul>
    
    {% endfor %}
{% endblock %}

auctions/templates/auctions/create_listing.html
{% extends 'auctions/layout.html' %}
{% block title %}A New Listing {% endblock %}


{% block body %}
<form action="{% url 'auctions:create-listing' %}" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{form}}
    <input type="submit" value="Create">
</form>
{% endblock %}

auctions/templates/auctions/inactive.html
{% extends "auctions/layout.html" %}
{% load static %}
{% block body %}
    <h2>Active Listings</h2>
    {% for listing in listings %}
        <div>
            <h1 style="text-align: left;" >{{listing.title}}</h1>
            <p>{{listing.description}}</p>
            <a href="{% url 'auctions:listing-detail' listing.id %}">
            <img src="../media/{{listing.image.name}}" alt="{{listing.title}}" style="width:450px;height:250px; text-align: center;">
        </a>
            <p><b>Price: </b>${{listing.price}}</p>

            <p1 style="font-family: Verdana, Geneva, Tahoma, sans-serif;">Created: {{listing.created}}</p1>
        </div><br><hr>
    {% empty %}
        <h1>There are no inactive listings.</h1>
    {% endfor %}
{% endblock %}

auctions/templates/auctions/index.html
{% extends "auctions/layout.html" %}

{% block body %}
    <h2>Active Listings</h2>

    TODO
{% endblock %}

auctions/templates/auctions/layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <title>{% block title %}Auctions{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'auctions/styles.css' %}" rel="stylesheet">
    </head>
    <body>
        <h1>Auctions</h1>
        <div>
            {% if user.is_authenticated %}
                Signed in as <strong>{{ user.username }}</strong>.
            {% else %}
                Not signed in.
            {% endif %}
        </div>
        <ul class="nav">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'auctions:index' %}">Active Listings</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'auctions:categories' %}">Categories</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'auctions:watchlist' %}">Watchlist</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'auctions:inactive' %}">Inactive Listings</a>
            </li>
            {% if user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'auctions:logout' %}">Log Out</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'auctions:create-listing' %}">Create A New Listing</a>
                </li>
            {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'auctions:login' %}">Log In</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'auctions:register' %}">Register</a>
                </li>
            {% endif %}
        </ul>
        <hr>
        {% block body %}
        {% endblock %}
    </body>
</html>

auctions/templates/auctions/listing_detail.html
{% extends 'auctions/layout.html' %}
{% block title %}
    {{listing.title}}
{% endblock %}
{% block body %}
<div>
    <h1 style="text-align: left;" >{{listing.title}}</h1>
    <p>{{listing.description}}</p>
    <img src="../media/{{listing.image.name}}" alt="{{listing.title}}" style="width:450px;height:250px; text-align: center;">
    {% if not listing.is_active %}
        <p><b>Original Price: </b>${{listing.price}}</p>

        <p1 style="font-family: Verdana, Geneva, Tahoma, sans-serif;">Created: {{listing.created}}</p1><br>
        <p1 style="font-family: Verdana, Geneva, Tahoma, sans-serif;">Ended: {{listing.closed}}</p1>
        <p><b>Current bid: ${{current_bid}}</b></p>
        <p1>Number of bid(s) : {{listing.number_of_bids}}</p1><br>
        <h3>Details</h3>
        <ul>
            <li>Listed by: {{listing.owner}}</li>
            <li>Category: {{listing.category}}</li>
            <li>Winner: {{listing.winner}}</li>
        </ul>
    {% else %}
        {% if listing.owner == request.user and listing.is_active %}
            <form action="{% url 'auctions:close-listing' %}" method="POST">
                {% csrf_token %}
                <input type="hidden" name="close_id" value="{{listing.id}}">
                <input type="submit" value="Close Auction"/>
            </form>
        {% endif %}
        
        {% if listing not in request.user.watchlist.all %}
            <form action="{% url 'auctions:watchlist' %}" method="POST">
                {% csrf_token %}
                <input type="hidden" name="watchlist_id" value="{{listing.id}}">
                <input type="hidden" name="add" value="1">
                <input type="submit" value="Add to watchlist"/>
            </form>
        {% else %}
        <form action="{% url 'auctions:watchlist' %}" method="POST">
            {% csrf_token %}
            <input type="hidden" name="watchlist_id" value="{{listing.id}}">
            <input type="hidden" name="add" value="0">
            <input type="submit" value="remove from watchlist"/>
        </form>
        {% endif %}
        <p><b>Original Price: </b>${{listing.price}}</p>

        <p1 style="font-family: Verdana, Geneva, Tahoma, sans-serif;">Created: {{listing.created}}</p1>
        <p><b>Current bid: ${{current_bid}}</b></p>
        <p1>Number of bid(s) so far: {{listing.number_of_bids}}</p1><br>
        {% if error%}
            {{error}}
        {%endif%}
        <form action="" method="POST">
            {% csrf_token %}
            {{form}}
            <input type="submit" value="Place">
        </form>
        </div><br><hr>
        <h3>Details</h3>
            <ul>
                <li>Listed by: {{listing.owner}}</li>
                <li>Category: {{listing.category}}</li>
            </ul>
    {% endif %}
    <h3>Comments:</h3>
    <form action="{% url 'auctions:comment'%}" method="POST">
        {% csrf_token %}
        <input type="text" name="comment" placeholder="Your comment">
        <input type="hidden" name="id" value="{{listing.id}}">
        <input type="submit" value="Comment">
    </form>
    {% for comment in comments %}
        <p>{{comment.owner}}: {{comment.text}}</p>
    {% empty %}
    <h3>No comments yet</h3>
    {% endfor %}
{% endblock %}

auctions/templates/auctions/login.html
{% extends "auctions/layout.html" %}

{% block body %}

    <h2>Login</h2>

    {% if message %}
        <div>{{ message }}</div>
    {% endif %}

    <form action="{% url 'auctions:login' %}" method="post">
        {% csrf_token %}
        <div class="form-group">
            <input autofocus class="form-control" type="text" name="username" placeholder="Username">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="password" placeholder="Password">
        </div>
        <input class="btn btn-primary" type="submit" value="Login">
    </form>

    Don't have an account? <a href="{% url 'auctions:register' %}">Register here.</a>

{% endblock %}

auctions/templates/auctions/register.html
{% extends "auctions/layout.html" %}

{% block body %}

    <h2>Register</h2>

    {% if message %}
        <div>{{ message }}</div>
    {% endif %}

    <form action="{% url 'auctions:register' %}" method="post">
        {% csrf_token %}
        <div class="form-group">
            <input class="form-control" autofocus type="text" name="username" placeholder="Username">
        </div>
        <div class="form-group">
            <input class="form-control" type="email" name="email" placeholder="Email Address">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="password" placeholder="Password">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="confirmation" placeholder="Confirm Password">
        </div>
        <input class="btn btn-primary" type="submit" value="Register">
    </form>

    Already have an account? <a href="{% url 'auctions:login' %}">Log In here.</a>

{% endblock %}

auctions/templates/auctions/watchlist.html
{% extends 'auctions/layout.html' %}
{% block title %}
    Watchlist
{% endblock %}
{% block body %}
{% for watchlist in watchlists %}
<div>
    <h1 style="text-align: left;" >{{watchlist.title}}</h1>
    <p>{{watchlist.description}}</p>
    <a href="{% url 'auctions:listing-detail' watchlist.id %}">
    <img src="../media/{{watchlist.image.name}}" alt="{{watchlist.title}}" style="width:450px;height:250px; text-align: center;">
</a>
    <p><b>Price: </b>${{watchlist.price}}</p>

    <p1 style="font-family: Verdana, Geneva, Tahoma, sans-serif;">Created: {{watchlist.created}}</p1>
    <form action="" method="POST">
        {% csrf_token %}
        <input type="hidden" name="watchlist_id" value="{{watchlist.id}}">
        <input type="hidden" name="add" value="0">
        <input type="submit" value="Remove from watchlist" />
    </form>
</div><br><hr>
{% empty %}
<h1>There are no active listings.</h1>
{% endfor %}
{% endblock %}